version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
